apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      containers:
        - name: library-service
          image: library-service:latest
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
